'NOTE: order of these is important, later ones override earlier ones

' double of default 96, for crisp image on 4k displays
skinparam dpi 192
skinparam useBetaStyle true

' avoid pointy notes
skinparam style strictuml

' avoid centered notes
skinparam NoteTextAlignment left

!$FONT_NAME_HUGE = "Century Gothic"
!$FONT_SIZE_HUGE = 20
!$FONT_NAME_LARGE = "Century Gothic"
!$FONT_SIZE_LARGE = 16
!$FONT_NAME_MEDIUM = "DejaVu Sans"
!$FONT_SIZE_MEDIUM = 12
!$FONT_NAME_SMALL = "Trebuchet MS"
!$FONT_SIZE_SMALL = 8

<style>
root {
    FontName: $FONT_NAME_LARGE
    Padding: $FONT_SIZE_LARGE
    RoundCorner: 32
    BackgroundColor: "Ivory"
}
Title {
    Margin: 32
    FontName: $FONT_NAME_HUGE
    FontSize: 32
    FontStyle: Regular
}
Header {
    FontSize: 16
    FontStyle: Italic
}
Interface {
    backgroundColor: $SYSTEM_BG_COLOR
    backgroundColor: $ARROW_COLOR
    .ext {
        backgroundColor: $EXTERNAL_SYSTEM_BG_COLOR
    }
}
Note {
    FontName: $FONT_NAME_SMALL
}
</style>


