apiVersion: v1
kind: Namespace
metadata:
  name: rbac
---
apiVersion: v1
kind: Namespace
metadata:
  name: sales
---
apiVersion: v1
kind: Namespace
metadata:
  name: utilities
---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Namespace
metadata:
  name: data


