@startuml

!theme carbon-gray
!include <C4/C4_Container>
!include doc/common/c4-custom-rel.iuml
!include doc/common/theme.iuml

' так сделано в изначальной схеме
SHOW_PERSON_OUTLINE()

title PropDevelopment — C4 Component
header «PropDevelopment»

AddElementTag("firewall", $bgColor="red")

Person(client, "Клиент", "Клиент")
Person(owner, "Собственник", "Клиент")
Person(manager, "Менеджер", "Работает с клиентами и объектами недвижимости, администрирует онлайн-сделки")
Person(accountant, "Бухгалтер", "Ведёт бухгалтерский учёт")
Person(business_analyst, "Бизнес-аналитик", "Оптимизирует процессы и развивает прикладные бизнес-системы. Администрирует системы")
Person(bi_analyst, "Аналитик BI", "Анализирует данные и готовит отчётность")

Container(firewall_client, "Firewall", $tags="firewall")
Container(firewall_owner, "Firewall", $tags="firewall")

System_Ext(gov_reg, "Государственные регистрационные органы", "Отвечают за регистрационные действия с объектами недвижимости")
System_Ext(payment_system, "Платёжная система", "Провайдер онлайн-платежей")
System_Ext(utility_provider, "Поставщик ресурсов ЖКХ")

Boundary(prop_development, "PropDevelopment") {
    Boundary(client_services, "Группа сервисов для клиентов") {
        Container(storefront, "Витрина продаж", "JavaScript, React", "Витрина для подбора и бронирования объектов недвижимости")
        Container(client_mart_estate_app, "client-mart-estate-app", "Kotlin, SpringBoot", "Приложение для управления информацией об объектах недвижимости")
        ContainerDb(client_mart_estate_db, "client-mart-estate-db", "PostgreSQL", "База данных объектов недвижимости")
        Container(client_mart_app, "client-mart-app", "Kotlin, SpringBoot", "Приложение для: - предоставления информации об объектах недвижимости, - проведения онлайн-сделок")
        ContainerDb(client_mart_db, "client-mart-db", "PostgreSQL", "База данных для хранения информации об объектах недвижимости и сделкам по ним")
        Container(client_tour_app, "client-tour-app", "Kotlin, SpringBoot", "Приложение для проведения 3D-тура по объекту недвижимости (онлайн-тур)")
        ContainerDb(client_tour_db, "client-tour-db", "PostgreSQL", "База данных проведения онлайн-тура")
        Container(client_crm_app, "client-crm-app", "e.g. SpringBoot, ElasticSearch, Dynamics CRM", "Система управления клиентскими данными")
        ContainerDb(crm_db, "crm-db", "MSSQL", "База данных системы CRM")

        Rel_D(storefront, client_mart_app, "", "REST")
        Rel_D(storefront, client_mart_estate_app, "Получить данные по объектам недвижимости", "REST")
        Rel_D(storefront, client_crm_app, "Регистрация клиента\nКарточка клиента\nПрофиль клиента", "REST")
        Rel_D(storefront, client_tour_app, "", "")

        Rel_D(client_mart_app, client_mart_db, "", "JDBC")
        Rel_D(client_mart_estate_app, client_mart_estate_db, "", "JDBC")
        Rel_D(client_crm_app, crm_db, "", "JDBC")
        Rel_D(client_tour_app, client_tour_db, "", "")

        Rel_L(client_crm_app, client_mart_app, "Публикация каталога объектов", "Kafka")
        Rel_R(client_crm_app, client_tour_app, "Публикация каталога объектов", "Kafka")

        Rel_U(client_mart_app, gov_reg, "СМЭВ", "SOAP")
        ' help keep client_mart_estate_app at left
        Lay_U(client_mart_estate_app, gov_reg)
    }

    Boundary(zku_services, "Группа сервисов ЖКУ") {
        Container(owner_apps, "Витрина сервисов для собственников", "Mobile app(iOS, Android)", "Мобильные приложения для собственников")
        Container(tenant_core_app, "tenant-core-app", "Kotlin, SpringBoot", "Приложение для предоставления услуг собственникам")
        ContainerDb(tenant_core_db, "tenant-core-db", "PostgreSQL", "База данных услуг ЖКХ по собственникам")
        Container(crm, "CRM", "Kotlin, Spring Boot", "Система управления данными собственников")
        ContainerDb(crm_tenant_db, "crm-tenant-db", "PostgreSQL", "База данных CRM по собственникам")

        Rel(owner_apps, tenant_core_app, "", "REST/WS")
        Rel(tenant_core_app, tenant_core_db, "", "JDBC")

        Rel(owner_apps, crm, "", "REST")
        Rel(crm, crm_tenant_db, "", "JDBC")

        Rel_L(tenant_core_app, crm, "Получение клиентских данных", "REST")
        Rel_D(tenant_core_app, payment_system, "")
        Rel_R(tenant_core_app, utility_provider, "")
    }

    Boundary(storage, "") {
        Container(dwh, "Хранилище данных", "Greenplum", "Единое хранилище данных для всех систем компании")
        ContainerDb(dwh_storage, "DWH Хранилище", "S3", "Физическое хранилище данных DWH")
        Rel(dwh, dwh_storage, "")

        Rel_D(client_mart_db, dwh, "Передача сырых данных", "CDC")
        Rel_D(client_mart_estate_db, dwh, "Передача сырых данных", "CDC")
        Rel_D(crm_db, dwh, "Передача сырых данных", "CDC")
        Rel_D(tenant_core_db, dwh, "Передача сырых данных", "CDC")
        Rel_D(crm_tenant_db, dwh, "Передача сырых данных", "CDC")
    }

    Boundary(accountant_group, "") {
        Container(accountant_service, "accountant-service-1", "Keycloak", "Система бухгалтерского учёта")
        Container(ad_apps, "Active Directory", "MS Active directory", "Служба каталогов, которая обслуживает прикладные бизнес-системы и системы обработки данных")
        ContainerDb(auth_db2, "auth-db-2", "PostgreSQL", "База данных сервиса аутентификации покупателей")

        Rel_L(accountant_service, auth_db2, "")
        Rel_R(accountant_service, ad_apps, "Аутентификация")
    }

    Boundary(auth_group, ""){
        Container(auth_service, "auth-service-1", "Keycloak", "Сервис аутентификации покупателей")
        ContainerDb(auth_db1, "auth-db-1", "PostgreSQL", "База данных сервиса аутентификации покупателей")
        Rel_U(auth_service, auth_db1, "")

        Rel_R(storefront, auth_service, "Регистрация\nАутентификация", "REST")
        Rel_L(owner_apps, auth_service, "Регистрация\nАутентификация", "REST")
    }

    Container(ad_data, "Active Directory", "MS Active directory", "Служба каталогов, которая обслуживает финансовые сервисы")
    Rel_D(client_crm_app, ad_data, "Аутентификация менеджеров")
    Rel_U(dwh, ad_data, "Аутентификация бизнес-аналитика")
    Rel_L(crm, ad_data, "Аутентификация менеджеров")
}

Rel_D(client, firewall_client, "")
Rel_D(firewall_client, storefront, "")

Rel_D(owner, firewall_owner, "")
Rel_D(firewall_owner, owner_apps, "")

Rel_D(business_analyst, prop_development, "")
Rel_D(manager, prop_development, "")

Rel_L(bi_analyst, dwh, "")

Rel_U(accountant, accountant_service, "")

Lay_R(dwh_storage, auth_db2)

@enduml

